blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('', views.PostListView.as_view(), name='index'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories', views.list_categories, name='categories'),
    path('categories/<int:category_id>', views.detail_category, name='detail_category'),
]

eosgatos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    titulo = models.CharField(max_length=255)
    conteudo = models.CharField(max_length=400)
    data_postagem = models.DateTimeField()
    img = models.URLField(max_length=200, null=True)
    criador = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.titulo} ({self.data_postagem})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data_postagem = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

    class Meta:
       ordering = ('-data_postagem',)

class Category(models.Model):
    titulo = models.CharField(max_length=255)
    description = models.CharField(max_length=400)
    post = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.titulo}'

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'titulo',
            'conteudo',
            'data_postagem',
            'img',
            'criador'
        ]
        labels = {
            'titulo': 'Título',
            'conteudo': 'Conteúdo',
            'data_postagem': 'Data',
            'img': 'URL da imagem do post',
            'criador': 'Criador'
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'data_postagem'
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
            'data_postagem':'Data'
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .temp_data import post_data
from django.urls import reverse, reverse_lazy
from .models import Post, Comment, Category
from django.views import generic
from .forms import PostForm, CommentForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView

class PostListView(generic.ListView):
    post = Post
    template_name = 'blog/index.html'

    def get_queryset(self):
        return Post.objects.order_by('-data_postagem')

class PostDetailView(generic.DetailView):
    post = Post
    template_name = 'blog/detail.html'

    def get_queryset(self):
        return Post.objects.all()

class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'blog/create.html'
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        return super().form_valid(form)

class PostUpdateView(UpdateView):
    form_class = PostForm
    template_name = 'blog/update.html'
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        return super().form_valid(form)

    def get_queryset(self):
        return Post.objects.all()

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')
    template_name = 'blog/delete.html'

    def get_object(self, queryset=None):
      post_id = self.request.POST.get('pk')
      return self.get_queryset().filter(pk=post_id).get()

def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'blog/detail.html', context)

def list_posts(request):
    post_list = Post.objects.all()
    context = {"post_list": post_list}
    return render(request, 'blog/index.html', context)

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_titulo = form.cleaned_data['titulo']
            post_conteudo = form.cleaned_data['conteudo']
            post_data_postagem = form.cleaned_data['data_postagem']
            post_img = form.cleaned_data['img']
            post_criador = form.cleaned_data['criador']
            post = Post(titulo=post_titulo,
                      conteudo=post_conteudo,
                      data_postagem=post_data_postagem,
                      img=post_img,
                      criador=post_criador)
            post.save()
            return HttpResponseRedirect(
                reverse('blog:detail', args=(post.id, )))
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'blog/create.html', context)

def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.titulo = request.POST['titulo']
            post.conteudo = request.POST['conteudo']
            post.data_postagem = request.POST['data_postagem']
            post.img = request.POST['img']
            post.criador = request.POST['criador']
            post.save()
            return HttpResponseRedirect(
                reverse('blog:detail', args=(post.id, )))
    else:
        form = PostForm(
            initial={
                'titulo': post.titulo,
                'conteudo': post.conteudo,
                'data_postagem': post.data_postagem,
                'img': post.img,
                'criador': post.criador
            })

    context = {'post': post, 'form': form}
    return render(request, 'blog/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('blog:index'))

    context = {'post': post}
    return render(request, 'blog/delete.html', context)

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment_data_postagem= form.cleaned_data['data_postagem']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            data_postagem=comment_data_postagem,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('blog:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'blog/comment.html', context)

def list_categories(request):
    categories_list = Category.objects.all().order_by('titulo')
    context = {"categories_list": categories_list}
    return render(request, 'blog/categories.html', context)

def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'blog/detail_category.html', context)

blog/templates/blog/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <section class="lista-de-posts">
        <h2>Categorias de posts</h2>
        
        {% if categories_list %}
            {% for category in categories_list %}
            <article class="post">
                <a class="button" href="{% url 'blog:detail_category' category.id %}"> 
                    <p>{{ category.titulo }}</p></a>
            </article>
            {% endfor %}
        {% else %}
        <p>Não foi encontrada nenhuma categoria de posts.</p>
        {% endif %}
    </section>

    <aside class="blog">
        <div>
            <h2>Crie seu post no nosso blog!</h2>
            <a class="button" href="{% url 'blog:create' %}"> 
                <p>Criar</p></a>
            
        </div>
        
    </aside>

</div>

    


{% endblock content %}

blog/templates/blog/comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <section class="form">
        <h2>Criar um comentário</h2>
        <form method="POST" action="{% url 'blog:comment' post.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Postar</button>
        </form>
        <a class="button voltar" href="{% url 'blog:detail' post.id %}" >Voltar</a>
    </section>
    
</div>

{% endblock content %}

blog/templates/blog/create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <section class="form">
        <h2>Criar um post</h2>
        <form method="POST" action="{% url 'blog:create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Postar</button>
        </form>
        <a class="button voltar" href="{% url 'blog:index' %}" >Voltar</a>
    </section>
    
</div>

{% endblock content %}

blog/templates/blog/delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <section>
        <form action="{% url 'blog:delete' post.id %}" method="post">
            {% csrf_token %}
            <p>
                Você tem certeza que deseja apagar o post de título "{{post.titulo}}"?
            </p>
            <button type="submit">Apagar</button>
        </form>
        <a class="button voltar" href="{% url 'blog:index' %}" >Voltar</a>
    </section>
    
</div>


{% endblock content %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.titulo }} ({{ post.data_postagem }})
{% endblock title %}

{% block content %}

<div class="container">
    <section class="lista-de-posts">
        <h2>{{ post.titulo }} ({{ post.data_postagem }})</h2>
        <p>{{post.conteudo}} </p>
        
        {%if post.img %}
            <img src="{{ post.img }}" alt="Post image" width="80%" height="auto">
        {% endif %}
        <p>Postado por: <i>{{ post.criador }}</i></p>
            
        <section>
            <h2>Comentários</h2>
            <ul>
                {% if post.comment_set.all %}
                    {% for comment in post.comment_set.all %}
                        <section class="comment">
                            <p> "{{ comment.text }}" </p>
                            <p> <i>Autor: </i>{{ comment.author }}</p>
                            <p><i>Postado em: </i> {{ comment.data_postagem }}</p>
                        </section>
                    {% endfor %}
                {% else %}
                    <p><i>Não há comentários para este post.</i></p>
                {% endif %}
            </ul>
        
            {% if post.category_set.all %}
            <p>Categorias deste post: {{ post.category_set.all|join:", " }} </p>
            {% endif %}
        </section>        

        <a class="button voltar" href="{% url 'blog:update' post.id %}" >Editar post</a>
        <a class="button voltar" href="{% url 'blog:delete' post.id %}" >Apagar post</a>
        <a class="button voltar" href="{% url 'blog:comment' post.id %}" >Postar um comentário</a>
        <a class="button voltar" href="{% url 'blog:index' %}" >Voltar</a>
    </section>

    <aside class="blog">
        <div>
            <h2>Crie seu post no nosso blog!</h2>
            <a class="button" href="{% url 'blog:create' %}"> 
                <p>Criar</p></a>
            
        </div>
        
    </aside>

</div>

{% endblock content %}

blog/templates/blog/detail_category.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <section class="lista-de-posts">
        <h2>{{ category.titulo }}</h2>
        <p>{{category.description}} </p>
        
        {% for post in category.post.all %}
            <article class="post">
                <a class="button" href="{% url 'blog:detail' post.id %}"><p>{{ post.titulo }}</p></a>
            </article>
            {% endfor %}

        <a class="button voltar" href="{% url 'blog:categories' %}" >Voltar</a>
    </section>

    <aside class="blog">
        <div>
            <h2>Crie seu post no nosso blog!</h2>
            <a class="button" href="{% url 'blog:create' %}"> 
                <p>Criar</p></a>
            
        </div>
        
    </aside>

</div>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <section class="lista-de-posts">
        <h2>Blog</h2>
        
        {% if post_list %}
            {% for post in post_list %}
            <article class="post">
                <a class="button" href="{% url 'blog:detail' post.id %}"> 
                    <p>{{ post.titulo }} ({{ post.data_postagem }})</p></a>
            </article>
            {% endfor %}
        {% else %}
        <p>Não foi encontrado nenhum post.</p>
        {% endif %}
    </section>

    <aside class="blog">
        <div>
            <h2>Crie seu post no nosso blog!</h2>
            <a class="button" href="{% url 'blog:create' %}"> 
                <p>Criar</p></a>
            
        </div>
        
    </aside>

</div>

    


{% endblock content %}

blog/templates/blog/update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <section class="form">
        <h2>Atualizar post</h2>
        <form method="POST" action="{% url 'blog:update' post.id%}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Atualizar</button>
        </form>
        <a class="button voltar" href="{% url 'blog:index' %}" >Voltar</a>
    </section>
    
</div>

{% endblock content %}