blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('', views.PostListView.as_view(), name='index'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories', views.list_categories, name='categories'),
    path('categories/<int:category_id>', views.detail_category, name='detail_category'),
]

eosgatos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('blog/', include('blog.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" type="imagex/png" href="{% static 'logo.svg' %}">
    <title>
        {% block title %}{% endblock %} | E os gatos?
    </title>
</head>

<body>
    <header>
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}" alt="logo" width="64" height="64"> </a> 
        <h1>E os gatos?</h1>
    </header>
    <nav>
        <div class="navigation-box">
            <a href="{% url 'index' %}" class="button">Home</a>    
        </div>
        <div class="navigation-box">
            <a href="{% url 'about' %}" class="button">Sobre</a>
        </div>
        <div class="navigation-box">
            <a href="{% url 'raças' %}" class="button">Raças mais populares no Brasil</a>
        </div>
        <div class="navigation-box">
            <a href="{% url 'blog:index' %}" class="button">Blog</a>
        </div>
        <div class="navigation-box">
            <a href="{% url 'blog:categories' %}" class="button">Categorias de posts</a>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>Copyright 2022 Sophia Celine.</p>
    </footer>
</body>

</html>